### ISSUE TITLE
Chemical Drug Screen

### ISSUE THREAD

**Issue by jstubbs01** [biof309/spring2019#1]
Hello Martin,

You directed me here to discuss potential help for a dataframe. I'll briefly describe what I'm trying to do. I am performing a chemical drug screen of cells. I have cultured and applied various drugs to these cells and then imaged them for several days. I also applied several dosages of drugs to these cells. After several days of imaging, I am analyzing my images. The software I am using outputs csv files containing cell counts. The goal is to plot cell death over time by measuring the change in cell number over several days. I am being challenged by the amount of dosages. I sought help in organizing my files (which number close to the 10,000s) by through a written R script that concatenates all the excel files into one large file and appends the following informative headers:

1. Drug
2. Dose
3. Day
4. Well
5. Plate (The cell type)
6. Total Cell Count (Puncta with Identifying Marker Color 1)
7. Total Puncta w/ Identifying Marker Color 2
8. Total Puncta w/ Identifying Marker Color 3
9. Puncta w/ Identifying Marker 1 and 3
10. Pattern (For the R Script)
11. Serial Number (for replicates, of which there are four)
12. Total Wildtype Cells (Number 6 Minus Number 9)
13. Another row of pattern for the R Script.

I am trying to compare Total Cell count over time, across multiple dosages, and also across several days.

**Comment by marskar** [comment]
Can share the R script and an example csv?  I'm not sure if making one giant file is the right approach if you just want a single number (cell count) from each file.
You could instead iterate through the files to build a data frame with the headers you provided.

**Comment by jstubbs01** [comment]
Hi Martin,

I sent you an email with my data and the notebook I used. I thought you could get the best sense of what my goal is by looking at that.
